# Generated by Django 3.1.8 on 2022-04-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=1000)),
                ("location_lat", models.FloatField()),
                ("location_lng", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("google_place_id", models.CharField(max_length=200, unique=True)),
                ("google_rating", models.FloatField()),
                ("google_user_ratings_count", models.IntegerField()),
            ],
        ),
    ]
