# Generated by Django 3.1.8 on 2022-04-26 19:19

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurants", "0002_auto_20220424_1328"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="location_lat",
            field=models.FloatField(validators=[restaurants.models.is_coordinate]),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="location_lng",
            field=models.FloatField(validators=[restaurants.models.is_coordinate]),
        ),
    ]
