# Generated by Django 3.0.6 on 2020-06-06 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starting_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="AgeGenderGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("men", models.PositiveIntegerField()),
                ("women", models.PositiveIntegerField()),
                ("boys", models.PositiveIntegerField()),
                ("girls", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GRANTED", "Asylum granted"),
                            ("ADDITIONAL", "Asylum granted with additional protection"),
                            ("HUMANITARIAN", "Asylum granted for humanitarian reasons"),
                            ("REJECTED", "Asylum rejected"),
                            ("DUBLIN", "Dublin regulation deportation"),
                            ("GRANTED_ELSEWHERE", "Asylum granted in another country"),
                            ("OTHER", "Other"),
                        ],
                        default="GRANTED",
                        max_length=50,
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="asylum.Year"
                    ),
                ),
            ],
        ),
    ]
