# Generated by Django 3.0.6 on 2020-06-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asylum", "0002_auto_20200606_1442"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="agegendergroup", unique_together={("status", "year")},
        ),
    ]
