# Generated by Django 3.0.6 on 2020-06-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asylum", "0004_auto_20200606_1643"),
    ]

    operations = [
        migrations.AddField(
            model_name="year",
            name="visible",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
