# Generated by Django 3.0.6 on 2020-06-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asylum", "0005_year_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="year",
            name="starting_date",
            field=models.DateField(help_text="January 1st of the year in question"),
        ),
    ]
