# Generated by Django 3.0.6 on 2020-06-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asylum", "0006_auto_20200607_1141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agegendergroup",
            name="boys",
            field=models.PositiveIntegerField(
                help_text="The number of non-adult boys in this age-gender group",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agegendergroup",
            name="girls",
            field=models.PositiveIntegerField(
                help_text="The number of non-adult girls in this age-gender group",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="agegendergroup",
            name="men",
            field=models.PositiveIntegerField(
                help_text="The number of men in this age-gender group", null=True
            ),
        ),
        migrations.AlterField(
            model_name="agegendergroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("GRANTED", "Asylum granted"),
                    ("ADDITIONAL", "Asylum granted with additional protection"),
                    ("HUMANITARIAN", "Asylum granted for humanitarian reasons"),
                    ("REJECTED", "Asylum rejected"),
                    ("DUBLIN", "Dublin regulation deportation"),
                    ("GRANTED_ELSEWHERE", "Asylum granted in another country"),
                    ("OTHER", "Other"),
                ],
                default="GRANTED",
                help_text="One of the final states of an asylum application as defined by the Directorate of Immigration",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="agegendergroup",
            name="women",
            field=models.PositiveIntegerField(
                help_text="The number of women in this age-gender group", null=True
            ),
        ),
        migrations.AlterField(
            model_name="year",
            name="visible",
            field=models.BooleanField(
                help_text="Whether to expose this year to clients"
            ),
        ),
    ]
