# Generated by Django 3.0.6 on 2020-05-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0003_gallery_identifier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery", options={"verbose_name_plural": "Galleries"},
        ),
    ]
