# Generated by Django 3.0.6 on 2020-05-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photos", "0005_auto_20200531_0930"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gallery",
            options={
                "ordering": ("start_date", "identifier"),
                "verbose_name_plural": "Galleries",
            },
        ),
        migrations.AddField(
            model_name="gallery",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
