# Generated by Django 3.0.7 on 2020-06-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_auto_20200531_2347"),
    ]

    operations = [
        migrations.RenameModel(old_name="FrontPageSection", new_name="Section",),
    ]
