# Generated by Django 3.0.7 on 2020-06-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_auto_20200628_1034"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="type",
            field=models.CharField(
                choices=[
                    ("FRONT_PAGE", "Front page section"),
                    ("PROJECT", "Project description"),
                ],
                default="FRONT_PAGE",
                help_text="A type of section, defining where it should be shown",
                max_length=50,
            ),
        ),
    ]
