# Generated by Django 3.0.7 on 2020-06-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_section_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section", old_name="type", new_name="category",
        ),
    ]
