# Generated by Django 3.0.7 on 2020-11-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0005_auto_20200628_1118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="category",
            field=models.CharField(
                choices=[
                    ("FRONT_PAGE", "Front page sections"),
                    ("PROJECTS", "Project sections"),
                ],
                default="FRONT_PAGE",
                help_text="A type of section, defining where it should be shown",
                max_length=50,
            ),
        ),
    ]
