# Generated by Django 3.0.7 on 2020-12-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0006_auto_20201129_1615"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="description",
            field=models.CharField(default="", max_length=280),
            preserve_default=False,
        ),
    ]
