# Generated by Django 3.0.7 on 2020-11-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="recipe", options={"ordering": ("name",)},),
    ]
