# Generated by Django 3.0.7 on 2020-12-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_auto_20201204_2233"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.CharField(
                default="",
                help_text="A more extended introduction to what this recipe is all about",
                max_length=280,
            ),
            preserve_default=False,
        ),
    ]
