# Generated by Django 3.0.7 on 2020-12-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_recipe_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
